name: Bedford Lab Research
description: Science updates on evolution, epidemiology and immunology from the Bedford lab at the Fred Hutch
url: http://bedford.io

markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title/

redcarpet: 
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

paginate: 6
paginate_path: "blog/page:num"
paginate_category: "blog"

exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.nb"
  - "*.trees"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"
  - "projects/nextflu/auspice/css/*"
  - "projects/nextflu/auspice/H3N2/*"
  - "projects/nextflu/auspice/H1N1pdm/*"
  - "projects/nextflu/auspice/Vic/*"
  - "projects/nextflu/auspice/Yam/*"
  - "projects/nextflu/auspice/muttree/*"        

projects:
  - trvrb/coaltrace
  - trvrb/stem
  - trvrb/PACT
  - trvrb/dynamics-practical
  - trvrb/antigen
  - trvrb/haplotypes
  - trvrb/divergence
  - trvrb/ancestry
  - trvrb/medium-data
  - blab/nextflu
  - alvason/infectious-pulse
  - blab/global-migration
